### ISSUE TITLE
Failed to generate executable file "opensbli_mpi" 

### ISSUE THREAD

**Issue by DDong1997** [opensbli/opensbli#3]
I meet an issue when I make the executable program "opensbli_mpi". Except that step 1.4.1 does not work and I changed it to "python3 $OPS_TRANSLATOR/ops.py opensbli.cpp", I have followed the installation instructions step by step before this problem and program on the recommended Ubuntu 18.04 platform, but it seems to have lost some functions or libraries. I have no idea which step I did wrong and how to fix it. I would be grateful if the issue could be solved. Some of the error messages are as follows:

OPS/ops/c/src/mpi/ops_mpi_hdf5.cpp:2516: undefined reference to `h5_type(char const*)'
OPS/ops//c/lib/gnu/libops_hdf5_mpi.a(ops_mpi_hdf5_mpi.o): In function `write_slab_buf_hdf5(char const*, char const*, ops_dat_core*, int const*, int const*, char const*)':
OPS/ops/c/src/mpi/ops_mpi_hdf5.cpp:2758: undefined reference to `split_h5_name(char const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'

**Comment by dl11g11** [comment]
This is a known issue on the OPS library and not related to the OpenSBLI code-generation. The Makefile in OPS/ops/c needs to be updated to include these recent HDF5 additions. The CMake system should work as an alternative.

It is already fixed in this branch: https://github.com/OP-DSL/OPS/tree/feature/restructure

Please try to either use CMake or check out this branch of OPS and recompile in the standard way.

**Comment by DDong1997** [comment]
Thanks for your help. The problem has been solved perfectly in this way.
